version: 2.1
executors:
  worker:
    docker:
      - image: fr3akyphantom/droid-builder:latest
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
jobs:
  build:
    executor: worker
    environment:
      MANIFEST_BRANCH: 'android-10.0'
      VENDOR: 'micromax'
      CODENAME: 'E7746'
      BUILD_LINK: '-O PBRP-E7746-3.0.0-20210130-0808-UNOFFICIAL.zip https://abhiramshibu.tuxforums.com/~iamsaalim/raza/PBRP-E7746-3.0.0-20210130-0808-BETA.zip'
      FLAVOR: 'eng'
      TEST_BUILD: 'true'
      MAINTAINER: 'PBRP Team'
      CHANGELOG: |
        - Initial Build
    working_directory: /home/builder/pitchblack
    steps:
      - run:
          name: AIO Build
          command: |
            wget -q https://raw.githubusercontent.com/raza231198/vendor_utils/test/pb_deploy_from_link.sh
            source pb_deploy_from_link.sh
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: 'release'
          context: org-global
